### DGL USER GUIDE

In [1]:
import numpy as np
import torch
import dgl
import networkx as nx
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
def drawnx(g):
    gx = dgl.to_networkx(g)
    nx.draw(gx, with_labels=True)

### NODES and EDGE features
https://docs.dgl.ai/en/0.8.x/guide/graph-feature.html#:~:text=A%20feature%20is%20created%20via,nodes%2Fedges%20in%20the%20graph.

In [3]:
g = dgl.graph(([0, 0, 1, 5], [1, 2, 2, 0]))
g

Graph(num_nodes=6, num_edges=4,
      ndata_schemes={}
      edata_schemes={})

In [5]:
g.ndata['x']=torch.ones(g.num_nodes(),3)
g.ndata['y']=torch.ones(g.num_nodes(),6)
g

Graph(num_nodes=6, num_edges=4,
      ndata_schemes={'x': Scheme(shape=(3,), dtype=torch.float32), 'y': Scheme(shape=(6,), dtype=torch.float32)}
      edata_schemes={})

In [8]:
g.ndata['y']

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

##### For weighted graphs, one can store the weights as an edge feature as below.


In [9]:
g.edata['x']=torch.zeros(g.num_edges(),2)
g

Graph(num_nodes=6, num_edges=4,
      ndata_schemes={'x': Scheme(shape=(3,), dtype=torch.float32), 'y': Scheme(shape=(6,), dtype=torch.float32)}
      edata_schemes={'x': Scheme(shape=(2,), dtype=torch.float32)})

In [10]:
g.edata['x']

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])

#### A heterogeneous graph can have nodes and edges of different types. Nodes/Edges of different types have independent ID space and feature storage.

In [12]:
torch.tensor([1,4])

tensor([1, 4])